### ISSUE TITLE
Offline mode deletes content

### ISSUE THREAD

**Issue by Willyfrog** [silverbulletmd/silverbullet#5] opened 2022-07-11 21:49 UTC
open same page on desktop and mobile

on mobile 
- turn on airplane mode
- write "this is mobile"

on desktop
- write "this is desktop

on mobile
- turn off airplan mode

Expected: somehow both lines, on obsidian I see that it creates a separate page with a number 2 (mentioning for reference), a conflict like git would also work.

Observed: mobile wins and desktop line is lost.

**Comment by zefhemel** [comment] 2022-07-14 17:41
A way to implement this is to add a type of “conditional put”. That is, “only write this page to disk, if the current timestamp matches X otherwise reject”. For the `http_space_primitives` (which is where this protocol is implemented between the browser and server) this may translate to an additional header to be sent as part of the `PUT` request.

**Comment by Willyfrog** [comment] 2022-07-14 19:09
I’ve been thinking about this and wondering if we could use some sort of patching functionality when updating a page, generating a conflict if it can’t be automatically solved (as git does)

**Comment by jzacsh** [comment] 2022-12-06 02:56
CRDTs maybe? I think the patch approach makes sense but will result in merge conflicts and the complex user experience the ensues, whereas CRDTs might solve this problem more smoothly. https://crdt.tech/implementations seems like a nice list of implementations and I know someone was getting to know the yjs lib in particular.

**Comment by ngrilly** [comment] 2022-12-06 10:46
I think Obsidian is solving this problem by just merging the server-side and the client-side content using a standard text merge algorithm like the one in `difftools`.

**Comment by ngrilly** [comment] 2022-12-06 17:10
@zefhemel Yes, Obsidian Sync.

**Comment by zefhemel** [comment] 2022-12-07 16:15
How I would imagine people use SB (at least I do) is to deploy just one instance (in your local network) and access it from multiple devices via the browser so you don't need to sync at all this avoiding such conflicts.

**Comment by jzacsh** [comment] 2022-12-07 16:18
Yeah, that makes sense. I suppose I take my laptop places a lot though (to the office, out to a bar/cafe, etc.) so maybe that's why I run into this issue a lot.

**Comment by lutzky** [comment] 2024-10-26 13:24
Bumping this issue because some matters discussed are stale (e.g. https://github.com/silverbulletmd/silverbullet/issues/449 removed the collab plugin). However, the issue still reproduces, even within a single-user use-case:

I use silverbullet for my packing list, with a template. I move around my house, throwing things in the suitcase and checking them off on my phone. Some of the things I do at my PC (e.g. checking in to the flight), so I leave that tab open... the current sync implementation does *not* like that.

Judging by the removal commit https://github.com/silverbulletmd/silverbullet/pull/451/commits/08d30866cb550016a01d86f87a467b3ab5a2e54d, my bright idea of "just use YJS for this, it looks great" appears to have already been attempted, and deemed too complicated to maintain. @zefhemel am I reading that correctly? Would you still consider the complexity of using yjs for sync too high? Even if it potentially replaces offline mode altogether?

**Comment by zefhemel** [comment] 2024-10-26 13:32
Yes, I really don't want to reintroduce Y.js or similar things, it complicates a lot of things.

When you say the current sync implementation does not like that, what do you mean, do you actually lose content or does it create a conflict? If you have a reproducible scenario please create an issue for it then I can look at it. I'll close this particular issue because it's so out of date.

**Closed by zefhemel** 2024-10-26 13:32 UTC
Labels: bug, help wanted

**Comment by lutzky** [comment] 2024-10-26 13:37
What I got was conflicts. I've been trying to reproduce today but couldn't quite get it (one of the infuriating things about sync issues eh).

Thanks for clarifying. I'll be sure to post an appropriate issue with reproduction instructions once I have something.
