### ISSUE TITLE
Sync mode takes too long to detect it's offline

### ISSUE THREAD

**Issue by justyns** [silverbulletmd/silverbullet#947] opened 2024-07-15 20:01 UTC
I'm pretty sure I saw a discussion about this recently, but didn't see a gh issue.

I'm traveling and noticed that whenever my phone is not connected to my VPN, I basically can't use the silverbullet pwa right after I open it.

After opening it, it takes 2 or 3 minutes for the index note to load. Once it does, I get the red status bar and things seem to work fine until I close and reopen the pwa later.

My guess without being able to see the console is maybe it's timing out trying to connect to my server. The dns would still resolve, but it'd be to a private ip.

**Comment by roceb** [comment] 2024-07-15 20:09
I have seen similar behaviour but since I have the pwa with Chrome, I
sometimes pop over to the chrome tab and it works and jump back to the pwa
and it works. Idk if it was a coincidence or not.

**Comment by zefhemel** [comment] 2024-07-17 18:38
Note to self, or whoever wants to give this a shot: https://github.com/silverbulletmd/silverbullet/blob/main/common/spaces/http_space_primitives.ts#L32

Likely we just have to add an explicit timeout to the linked fetch call. An AbortController https://developer.mozilla.org/en-US/docs/Web/API/AbortController can be used for this. Question is what a reasonable timeout would be. Perhaps 5 seconds?

**Comment by justyns** [comment] 2024-07-20 04:16
thanks for the hint, I can take a look at it this weekend if no one else has already started working on it.

I'd probably make the timeout configurable with an environment variable just in case, but 5 seconds is probably fine imo. 

Would it make sense to change the default behavior of the app to assume it is offline?   And then go into online mode (or whatever its called) once it's made a successful connection?  I think that could make the editor immediately usable when you open the PWA.

**Comment by zefhemel** [comment] 2024-07-20 04:33
Yes that can make sense. Probably it shouldn't show the yellow in UI immediately though, that would confuse people probably.

**Comment by roceb** [comment] 2024-07-20 06:59
I made a draft for it. I do not develop in TS, or in deno. So feedback would be great #965

**Comment by zefhemel** [comment] 2024-07-22 15:36
Ok that's merged, let's see if this helps.

**Comment by zefhemel** [comment] 2024-07-23 19:12
Ok closing this seems a bit premature, please let me know if this helped.

**Comment by roceb** [comment] 2024-07-23 19:41
I tried to reproduce it on my phone and tablet. And it seems to have worked just fine. I also haven't noticed the offline message since I updated edge. So 1 vote for closing.

**Comment by zefhemel** [comment] 2024-07-28 07:10
Let me close this. We can reopen if this is still and issue after the new timeout limits.

**Closed by zefhemel** 2024-07-28 07:10 UTC

**Comment by justyns** [comment] 2024-07-28 23:19
I forgot to reply the other day, but I tested this on my phone and it's definitely a lot better.  There's still a delay where some actions take ~5s before they happen,  but it's way more usable

**Comment by justyns** [comment] 2024-08-02 05:46
Following up on this, I think there are now different intermittent issues.  Sometimes my server is really slow when I first open silverbullet and the index.json GET request is timing out.  It retries it a couple times and usually fails, but eventually works.

<img width="1041" alt="image" src="https://github.com/user-attachments/assets/3c181a92-e886-4319-bffc-009ed0787a50">

When it's doing this, I just have a white screen and can't do anything.  I've also noticed fetching plugs and libraries causes an error in the console because it doesn't wait long enough for the server to finish the update process, though it does still work.

> federation.plug.js:1 An exception was thrown as a result of invoking function updateLibrariesCommand error: signal timed out
> editor_ui.tsx:146 Error running command signal timed out


Ideally we'd have a separate timeout for connect instead of the total request time, but I don't see a way to do that with fetch/abortcontroller.
