### ISSUE TITLE
Allow tags to start with a numeral

### ISSUE THREAD

**Issue by jaduff** [silverbulletmd/silverbullet#1072] opened 2024-08-31 10:19 UTC
Starting tags with a numeral kinda works, but the tag isn't highlighted in blue showing its recognised as a tag, and autocomplete doesn't work. Queries based on the tag still work though.
My use-case is that I'm following the filing system 'Johnny Decimal' which allows creating consistent filing across areas like notes, email, electronic folders, and physical folders. But this requires that the name starts with a numeric id.

**Comment by lutzky** [comment] 2024-09-17 20:59
My use case: I tag my projects into categories, and one of them  is #3dprint :shrug:

**Comment by leamsi** [comment] 2024-10-11 18:09
Sharing my experience and adding another +1 to this request:

I like to tag my pages based on topics using a hierarchy based off the Johnny Decimal system (https://johnnydecimal.com). Except I'm using dashes instead of periods because so many tools get confused by periods in tags. So these tags look like this: #10-11-Personal-Health ... and this works fine with vimwiki, nb, and zk (other tools I use to handle my personal notes). I'm trying to make silverbullet the way to access my notes online and I mostly really like it except for small paper cuts like this.

I think just supporting anything that matches `\w` as a first character would be great in terms of interoperability with other Markdown tools, but of course, I don't understand the reason why that isn't the way it works in SB.

**Comment by Maarrk** [comment] 2024-10-13 12:10
> I don't understand the reason why that isn't the way it works in SB.

I would guess that it's to stop things like Issue #123456 becoming a tag, which one might use to refer to a magazine.

The specific regular expression that matches what is parsed as hashtag is here:
https://github.com/silverbulletmd/silverbullet/blob/4b6cd183a82e18df864347f813615cc5f7c2b823/common/markdown_parser/constants.ts#L3-L4

It can be summarised as:
- 1 instance of `#`
- 1 instance of not digit (`\d`), not whitespace (`\s`), and not a bunch of interpunction
- 0 or more of not whitespace (`\s`), and not a bunch of other interpunction

So it's not a bug but put here by design.

---

The proposed rules could be implemented with some Regex complication:
- Allow to start with a digit if there's some other stuff after it
- Alternatively match against a sequence delimited with `"`, `'` or between `<`,`>`  but allow anything inside it (this can gobble up the whole document if not escaped)

To make the discussion accessible for everyone, I've copied some quotes from here into an external website. We can use to test the ideas, but there's also explanations of how the pattern works. Here's the link: https://regex101.com/r/Zegl8q/3

![obraz](https://github.com/user-attachments/assets/fdd9a4b8-d4bb-4411-8f5f-d587bc04822e)

**Comment by zefhemel** [comment] 2024-10-13 14:50
Nice! I think this is a reasonable trade-off. Happy to take a PR 😅

**Comment by zefhemel** [comment] 2024-10-13 14:50
Nice! I think this is a reasonable trade-off. Happy to take a PR 😅

**Comment by Maarrk** [comment] 2024-10-14 18:50
Having done a practical implementation in #1116 I found two new issues with the escaping syntax to discuss:

## Ignore escaping type

currently there are no capture groups, so `#content`, `#"content"` and `#<content>` give different results, as seen in the query below. I'd need to look more into how these are moved into Object attributes, maybe just remove the terminators there, because I don't want to complicate the parse tree with HashtagMark as it is for wikilink `[[` to not include it in the content.

## Escaping with quotes

Depending on the user's setting of `useSmartQuotes` they may input `“ ”` which are different from `"` used in regex. If #1114 lands, these will be completely unpredictable, so probably better to avoid them in the regex altogether. Do y'all thing (especially @mjf) that just supporting `#<tag with spaces>` is enough? I completely skip the backslash escape from the start, because it happened to be more complicated to implement with regex.

![obraz](https://github.com/user-attachments/assets/35685504-17ac-47d9-b1d8-25362df75bff)

**Comment by Maarrk** [comment] 2024-10-15 08:00
Ad 2: Note that single quotes are already allowed in tags, so I wouldn't change that unless really well motivated. I'd say that having it as a fourth (!) way of escaping characters is a bit too much.

These are some examples I can think of where a single quote is naturally included:
![screenshot of tags with single quotes](https://github.com/user-attachments/assets/8198e878-7560-452e-9428-3dba975ca325)

You could argue that if the single quote is at the start of tag, it's probably not part of any English grammar but that also feels like complicating it.

---

> 1. `#<some tag name even including escaped \> characters>`

With your idea for escaping the terminating `>` I think it's enough to do only this one and call it a day. It would allow to get any string inside the tag name.

> I now think that EOLs should not be part of a tag name, except those escaped like:

I'm still on the side of explicitly disallowing multiline tags, so if you don't close it, wouldn't devour the whole rest of the document. Also regex gets weird around multiline stuff.

**Comment by zefhemel** [comment] 2024-10-15 12:44
I don't have very strong opinions here to be honest. Personally I was fine with the constraints that existed so far, but I can see why adding some more flexibility can be useful. I know LogSeq uses the `#[[multiple word]]` syntax, but I that's indeed a bit nasty with the current parser, so perhaps using `#<multiple words>` is ok, since the `<` and `>` is also a valid way to use multi word URLs in e.g. markdown links. Supporting tags with multi lines doesn't make sense to me, so I wouldn't try to support that.

One thing I would like to make sure is that we have one single source of parsing truth for parsing these tags, and not multiple regexes floating around the code base.

**Comment by Maarrk** [comment] 2024-10-15 22:53
The discussion was getting really long, so I decided to support just two new things for now:
1. Allow tags to start with a numeral
2. Tags with included spaces can be written as `#<tag with spaces>`

I have tested the following features, let me know if I'm missing anything:
- Correctly parsing in the markdown document (with unit test)
- Styling in the page
- Opening the tag page when clicked
- Indexing for queries
- Auto-completion

![obraz](https://github.com/user-attachments/assets/3e516ef0-e64f-4111-9ea5-37ee3dae1c29)

---

With the `#<new syntax>` it's unavoidable that the code that was just adding or removing the `#` at the start will no longer work correctly. I added two new functions `hashtagName` and `hashtagText` defined just below the code that defines the Hashtag node, to keep them up to date with the parser.

It may be useful to expose functions to templates somehow, but I'm not sure what would be the best way, and if the names need to be updated before that.

---

> One thing I would like to make sure is that we have one single source of parsing truth for parsing these tags, and not multiple regexes floating around the code base.

I was on the lookout for this, and the only other one I found is for triggering completion, here:
https://github.com/silverbulletmd/silverbullet/blob/413855c1809dac92ea10d0a22c041cd6077f7844/plugs/index/tags.ts#L61

I only adjusted it slightly to allow a digit after the `#`

**Closed** 2024-10-20 10:39 UTC
Labels: enhancement
