### ISSUE TITLE
Feature Request: Table of Contents

### ISSUE THREAD

**Issue by jwalzer** [silverbulletmd/silverbullet#375] opened 2023-02-27 23:39 UTC
### description

I would like a plug that allows me to create a Table of Contents in my page. A special Tag `<!-- TOC --> .... <!-- EndToc -->` could be used to embed the current hierarchy. Of course a nice addon would be if a quick-command `/toc` would exist.

The ToC should be created from the headlines of the paragraph of the document. The titles should be a link to the headline it was generated from.

**Comment by zefhemel** [comment] 2023-02-28 09:12
Duplicate of #263 could you add your suggestions there?

**Closed by zefhemel** 2023-02-28 09:12 UTC
