### ISSUE TITLE
[bug] Inline-images are not handled when renaming pages

### ISSUE THREAD

**Issue by NeilHanlon** [silverbulletmd/silverbullet#789] opened 2024-03-05 16:50 UTC
When you rename a page which has an image in it (e.g., from using the AI Plug's DallE feature), in such a way that the page is located in a different folder, the relative link used in the image markdown tag is not updated to reflect the change in path, nor is the image moved to the location of the new page so the relative link functions.

**Comment by zefhemel** [comment] 2024-03-05 19:19
I think this is a duplicate of #733

**Closed by zefhemel** 2024-03-05 19:19 UTC
